sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
jdk:
  - openjdk8
script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - sbt ++$TRAVIS_SCALA_VERSION test
  - kill %1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
